#!/usr/bin/env bash
# gen-env.sh — generate .env with host ports that are ACTUALLY bindable on this
# machine right now.
#
# WHY THIS EXISTS (Windows-specific, important)
#   Hyper-V/WSL reserves dynamic TCP "excluded port ranges" at boot. They SHIFT
#   on every reboot. A port hardcoded in docker-compose.yml (e.g. 13000) can
#   silently fall inside a reserved range and fail with:
#     "bind: An attempt was made to access a socket in a way forbidden by its
#      access permissions"
#   This is NOT a permission bug — the port is reserved by WinNAT.
#
#   Rather than hardcode "safe" ports (which stop being safe after a reboot),
#   we probe the live excluded ranges, pick free ports outside them, and write
#   them to .env. docker-compose.yml already reads these variables.
#
# USAGE
#   ./scripts/gen-env.sh            # write .env (preserves non-port settings)
#   ./scripts/gen-env.sh --check    # report which configured ports are blocked
#
# Ports chosen (all outside excluded ranges, not already listening):
#   KLEIDION_DB_HOST_PORT          (postgres)
#   KLEIDION_API_HOST_PORT         (go server)
#   KLEIDION_WEB_HOST_PORT         (next dev)
#   KLEIDION_MAIL_UI_HOST_PORT     (mailpit UI)
#   KLEIDION_SMTP_HOST_PORT        (mailpit SMTP)

set -euo pipefail

cd "$(dirname "$0")/.."

log() { printf '[gen-env] %s\n' "$*"; }

IS_WINDOWS=0
uname -s 2>/dev/null | grep -qiE 'mingw|msys|cygwin' && IS_WINDOWS=1

# Collect excluded port ranges (Windows only). Output: "start end" per line.
excluded_ranges() {
  [ "$IS_WINDOWS" = 1 ] || return 0
  netsh interface ipv4 show excludedportrange protocol=tcp 2>/dev/null \
    | grep -E '^[[:space:]]+[0-9]+[[:space:]]+[0-9]+' \
    | awk '{print $1, $2}'
}

# Collect ports already LISTENING on this host.
listening_ports() {
  if command -v netstat >/dev/null 2>&1; then
    netstat -ano 2>/dev/null | awk '/LISTENING/ {print $2}' \
      | sed -E 's/.*[:.]([0-9]+)$/\1/' | sort -un
  fi
}

EXCLUDED="$(excluded_ranges)"
LISTENING="$(listening_ports)"

is_excluded() {
  local p="$1" s e
  while read -r s e; do
    [ -z "$s" ] && continue
    if [ "$p" -ge "$s" ] && [ "$p" -le "$e" ]; then return 0; fi
  done <<< "$EXCLUDED"
  return 1
}

is_listening() {
  local p="$1"
  grep -qx "$p" <<< "$LISTENING"
}

# port_free <candidate> -> 0 if bindable
port_free() {
  local p="$1"
  is_excluded "$p" && return 1
  is_listening "$p" && return 1
  return 0
}

# find_port <preferred> <min> <max> -> prints a free port
find_port() {
  local pref="$1" min="$2" max="$3" p
  if port_free "$pref"; then echo "$pref"; return 0; fi
  # Preferred is taken/excluded — scan upward from min.
  for ((p = min; p <= max; p++)); do
    if port_free "$p"; then echo "$p"; return 0; fi
  done
  echo ""
  return 1
}

# Read an existing value from .env if present.
env_val() {
  local key="$1"
  [ -f .env ] || { echo ""; return 0; }
  sed -nE "s/^${key}=(.*)$/\1/p" .env | tail -1
}

declare -A PREF=(
  [KLEIDION_DB_HOST_PORT]=15432
  [KLEIDION_API_HOST_PORT]=18080
  [KLEIDION_WEB_HOST_PORT]=13000
  [KLEIDION_MAIL_UI_HOST_PORT]=18025
  [KLEIDION_SMTP_HOST_PORT]=11025
)

if [ "${1:-}" = "--check" ]; then
  log "checking configured ports against WinNAT excluded ranges"
  for key in "${!PREF[@]}"; do
    cur="$(env_val "$key")"; cur="${cur:-${PREF[$key]}}"
    if is_excluded "$cur"; then
      log "BLOCKED  $key=$cur  (inside a WinNAT excluded range — re-run without --check)"
    elif is_listening "$cur"; then
      log "IN USE   $key=$cur  (something else is listening)"
    else
      log "ok       $key=$cur"
    fi
  done
  exit 0
fi

DB_PORT="$(find_port "${PREF[KLEIDION_DB_HOST_PORT]}" 15432 15999)"
API_PORT="$(find_port "${PREF[KLEIDION_API_HOST_PORT]}" 18080 18999)"
WEB_PORT="$(find_port "${PREF[KLEIDION_WEB_HOST_PORT]}" 23000 23999)"
MAIL_UI_PORT="$(find_port "${PREF[KLEIDION_MAIL_UI_HOST_PORT]}" 28025 28099)"
SMTP_PORT="$(find_port "${PREF[KLEIDION_SMTP_HOST_PORT]}" 21025 21099)"

for pair in "DB:$DB_PORT" "API:$API_PORT" "WEB:$WEB_PORT" "MAILUI:$MAIL_UI_PORT" "SMTP:$SMTP_PORT"; do
  [ -z "${pair#*:}" ] && { log "ERROR: could not find a free port for ${pair%%:*}"; exit 1; }
done

# Preserve existing secrets/settings from .env if present.
DB_PW="$(env_val KLEIDION_DB_PASSWORD)"; DB_PW="${DB_PW:-kleidion_dev_pw}"
SECRET="$(env_val KLEIDION_SESSION_SECRET)"
if [ -z "$SECRET" ]; then
  SECRET="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
fi

cat > .env <<EOF
# GENERATED by scripts/gen-env.sh — host ports are chosen to avoid the
# WinNAT/Hyper-V excluded-port ranges AND ports already in use on this machine.
# Re-run ./scripts/gen-env.sh after a reboot if a port stops binding.
KLEIDION_ENV=development
KLEIDION_PORT=8080

KLEIDION_DB_PASSWORD=${DB_PW}
# For running the server OUTSIDE compose (bare \`go run\` on the host):
KLEIDION_DATABASE_URL=postgres://kleidion:${DB_PW}@localhost:${DB_PORT}/kleidion?sslmode=disable
KLEIDION_SESSION_SECRET=${SECRET}

# Host port mappings (container-side ports stay canonical: 5432/8080/3000/8025/1025)
KLEIDION_DB_HOST_PORT=${DB_PORT}
KLEIDION_API_HOST_PORT=${API_PORT}
KLEIDION_WEB_HOST_PORT=${WEB_PORT}
KLEIDION_MAIL_UI_HOST_PORT=${MAIL_UI_PORT}
KLEIDION_SMTP_HOST_PORT=${SMTP_PORT}

NEXT_PUBLIC_API_URL=http://localhost:${API_PORT}
EOF

log "wrote .env"
log "  db      -> localhost:${DB_PORT}"
log "  api     -> http://localhost:${API_PORT}"
log "  web     -> http://localhost:${WEB_PORT}"
log "  mailpit -> http://localhost:${MAIL_UI_PORT}"
